name: Electron Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager -g
        working-directory: DndHelper

      - name: Build Linux Electron app
        working-directory: electronDnd
        run: ./linux_setup.sh

  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager -g
        working-directory: electronDnd

      - name: Build macOS Electron app
        run: ./mac_setup.sh
        working-directory: electronDnd
