name: Electron Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager

      - name: Build Linux Electron app
        run: electron-packager . DnDHelper --platform=linux --arch

  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager

      - name: Build macOS Electron app
        run: electron-packager . DnDHelper --platform=darwin --arc
