name: Electron Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager -g
        working-directory: DndHelper

      - name: Build Linux Electron app
        run: electron-packager . DndHelper --platform=linux --arch=x64 --electronVersion=2.0.9 --icon=assets/ico/d20.ico
        working-directory: DndHelper

  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install electron-packager -g
        working-directory: DndHelper

      - name: Build macOS Electron app
        run: electron-packager . DndHelper --platform=darwin --arch=x64 --electronVersion=2.0.9 --icon=assets/icns/d20.icns
        working-directory: DndHelper
